feat: allow eslint-plugin-promise 6
standard/eslint-config-standard pull request #198
Opened 2021-12-22 23:17 UTC by nschonni

Expand the peerDependency and add a CI matrix to test it

2021-12-22 23:18 UTC, nschonni commented on package.json
> +    "eslint-plugin-promise": "^4.2.1 || ^5.0.0 || ^6.0.0"
Alternatly, this could just change to `>=4.21`, keep the testing, and update the matrix

2021-12-23 00:47 UTC, voxpelli commented
Would be helpful with an explanation of why this new major version isn't breaking from our perspective.

2021-12-23 00:51 UTC, nschonni commented
The v6 is more about ESLint 8 compat, but I added the CI testing to ensure that there is not conflicts going forward, since you seem to have set v4 as a baseline

2021-12-23 00:54 UTC, voxpelli commented
Right. Looks like it's the node version that's the breaking change

2021-12-23 01:01 UTC, nschonni commented
I can add the Node version matrix as well here if you want

2021-12-23 08:57 UTC, voxpelli commented on .github/workflows/ci.yml
> +        eslint-plugin-promise:
I would prefer to have this in something like a `compat.yml`, to keep the main CI file as lean as possible

2021-12-23 08:57 UTC, voxpelli commented on package.json
> +    "eslint-plugin-promise": "^4.2.1 || ^5.0.0 || ^6.0.0"
I like specifying the upper version that complies with the standard rule set, so an upgrade doesn't cause unintentional rule changes

2021-12-23 08:58 UTC, voxpelli commented
> I can add the Node version matrix as well here if you want

Not necessary I think

2021-12-23 14:17 UTC, nschonni commented on .github/workflows/ci.yml
> +        eslint-plugin-promise:
Extra YML files here would be interpreted as malformed workflow files. Might be something for when you go for the org-wide action approach and need a repo specific override file

2021-12-28 12:23 UTC, Divlo requested changes
Hey! :smile:

Thanks for your PR, but this will already be fixed by this PR: https://github.com/standard/eslint-config-standard/pull/193 that hopefully, we will soon merge and release, it is ready, I'm waiting for reviews.

2021-12-28 17:32 UTC, nschonni commented
@Divlo yeah, I'm aware of the other PR, but it seems stalled because of the multiple changes. I opened this to fix one of the issues the other PR was dealing with that should be easier to land

2022-01-07 17:13 UTC, Divlo commented
The PR #193 has been landed and released in the prerelease `17.0.0-0`.

2022-01-07 17:13 UTC, closed without merging